---
- hosts: localhost 
  become: yes
  name: jenkins-installer
  tasks:
    - name: create jenkins directory
      file: state=directory path=/etc/yum.repos.d/jenkins.repo

    - name: download sources
      get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo

    - rpm_key:
        state: present
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

    - name: installing jenkins
      yum:
        name: jenkins
        state: latest